#!/usr/bin/env ruby

print ("%i%%%s" % `pmset -g ps`.scan(/(\d+)%; (\w*);/).flatten).gsub("discharging", "-").gsub("charging", "+").gsub("charged", "=")
print ' '
print (`pmset -g batt | grep Internal | awk '{print $4}'`)
