brew "mas"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "AdoptOpenJDK/openjdk"

brew "autoconf"
brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "bindfs"
brew "cmake"
brew "colordiff"
brew "coreutils"
brew "ctags"
brew "curl"
brew "direnv"
brew "fortune"
brew "gdbm"
brew "git"
brew "glib"
brew "gnu-tar"
brew "htop"
brew "httpie"
brew "hub"
brew "jq"
brew "keychain"
brew "libtool"
brew "loc"
brew "make"
brew "mtr"
brew "markdown"
brew "magic-wormhole"
brew "memcached"
brew "neovim"
brew "nethogs"
brew "nmap"
brew "openssl"
brew "pivotal/tap/git-together"
brew "pkg-config"
brew "python"
brew "qemu"
brew "rbenv"
brew "rbenv-vars"
brew "readline"
brew "reattach-to-user-namespace"
brew "rsync"
brew "ruby-build"
brew "smartypants"
brew "speedtest-cli"
brew "sshfs"
brew "sshuttle"
brew "tcpdump"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "unzip"
brew "watch"
brew "wget"

cask "osxfuse"
cask "adoptopenjdk11"
cask "alfred"
cask "bettertouchtool"
cask "cursorcerer"
cask "docker"
cask "dropbox"
cask "iterm2"
cask "stay"
cask "intellij-idea"

mas "1Password", id: 1333542190
mas "Things 3", id: 904280696
mas "Focus", id: 777233759
mas "1Blocker", id: 1107421413
