install ag
install bash
install bash-completion
install cmake
install colordiff
install coreutils
install cscope
install ctags
install freetype
install git
install htop-osx
install macvim --override-system-vim
install markdown
install memcached
install multimarkdown
install nginx
install python
install rbenv
install rbenv-vars
install readline
install reattach-to-user-namespace
install redis
install ruby-build
install smartypants
install tmux
install tree
